### ISSUE TITLE
Acrobat DC

### ISSUE THREAD

**Issue by TobiasNisius** [UB-Mannheim/sci-work-course#131]
This is how the settings for Adobe Acrobat DC should look like

![image](https://cloud.githubusercontent.com/assets/23309355/20104391/22e70878-a5ce-11e6-906a-3eed819e211d.png)

**Comment by kba** [comment]
Is that a screenshot of how it should be configured or a do you have a problem with your settings?

**Comment by zuphilip** [comment]
I asked him for a screenshot, because there was a problem with automatically opening with Acrobat DC (not Viewer) from TexnicCenter. @TobiasNisius Maybe you can make another screenshot from the `Viewer` tab where the Acrobat commands stand? It was substituting `acroviewR15` by `acroviewA15` and otherwise follow the [solution for Acrobat DC Viewer](https://tex.stackexchange.com/questions/250472/texniccenter-adobe-reader-dc).

**Comment by TobiasNisius** [comment]
Sorry you're right. In the hurry I did the wrong screenshot. This is how the settings for Adobe DC should look like:

![image](https://cloud.githubusercontent.com/assets/23309355/20104379/1a5c6054-a5ce-11e6-8b77-b5511de6287a.png)
